import { JOB_DETAILS } from "./job-details";

export type WorkMode = "remote" | "hybrid" | "onsite";
export type Seniority = "junior" | "mid" | "senior" | "lead" | "staff";
export type JobFunction =
  | "design"
  | "engineering"
  | "product"
  | "data"
  | "marketing"
  | "sales";
export type Culture = "startup" | "scaleup" | "corporate";

export type Job = {
  id: string;
  company: string;
  role: string;
  city: string;
  workMode: WorkMode;
  salaryMin: number;
  salaryMax: number;
  seniority: Seniority;
  fn: JobFunction;
  stack: string[];
  culture: Culture;
  teamSize: number;
  onCall: boolean;
  fourDayWeek: boolean;
  summary: string;
  description: string;
  responsibilities: string[];
  requirements: string[];
};

const RAW_JOBS: Omit<Job, "description" | "responsibilities" | "requirements">[] = [
  {
    id: "linear-spd",
    company: "Linear",
    role: "Senior Product Designer",
    city: "Berlin",
    workMode: "hybrid",
    salaryMin: 85,
    salaryMax: 110,
    seniority: "senior",
    fn: "design",
    stack: ["figma", "research", "systems"],
    culture: "startup",
    teamSize: 8,
    onCall: false,
    fourDayWeek: false,
    summary: "8 Designer, jede Woche shippen, kein Committee.",
  },
  {
    id: "pitch-lead",
    company: "Pitch",
    role: "Lead Product Designer",
    city: "Berlin",
    workMode: "hybrid",
    salaryMin: 90,
    salaryMax: 120,
    seniority: "lead",
    fn: "design",
    stack: ["figma", "brand", "product"],
    culture: "startup",
    teamSize: 12,
    onCall: false,
    fourDayWeek: false,
    summary: "Lead mit Team, Brand sitzt im Produkt, Berlin HQ.",
  },
  {
    id: "personio-pd",
    company: "Personio",
    role: "Product Designer",
    city: "München",
    workMode: "remote",
    salaryMin: 80,
    salaryMax: 95,
    seniority: "mid",
    fn: "design",
    stack: ["figma", "research"],
    culture: "scaleup",
    teamSize: 40,
    onCall: false,
    fourDayWeek: false,
    summary: "40 Designer, Research-Ops, Remote aus Deutschland.",
  },
  {
    id: "raycast-pd",
    company: "Raycast",
    role: "Product Designer",
    city: "Remote",
    workMode: "remote",
    salaryMin: 88,
    salaryMax: 115,
    seniority: "senior",
    fn: "design",
    stack: ["figma", "macos", "systems"],
    culture: "startup",
    teamSize: 6,
    onCall: false,
    fourDayWeek: true,
    summary: "6 Leute, du designst was in der Menüleiste landet. 4 Tage.",
  },
  {
    id: "polar-staff",
    company: "Polar",
    role: "Staff Engineer",
    city: "Remote",
    workMode: "remote",
    salaryMin: 110,
    salaryMax: 140,
    seniority: "staff",
    fn: "engineering",
    stack: ["go", "kubernetes", "postgres"],
    culture: "startup",
    teamSize: 18,
    onCall: false,
    fourDayWeek: true,
    summary: "Open Source, Go, keine Bereitschaft, vier Tage.",
  },
  {
    id: "langfuse-be",
    company: "Langfuse",
    role: "Backend Engineer",
    city: "Berlin",
    workMode: "hybrid",
    salaryMin: 75,
    salaryMax: 95,
    seniority: "mid",
    fn: "engineering",
    stack: ["typescript", "node", "postgres"],
    culture: "startup",
    teamSize: 14,
    onCall: false,
    fourDayWeek: false,
    summary: "LLM-Observability, TypeScript, zwei Tage Office.",
  },
  {
    id: "n26-be",
    company: "N26",
    role: "Backend Engineer",
    city: "Berlin",
    workMode: "hybrid",
    salaryMin: 92,
    salaryMax: 118,
    seniority: "senior",
    fn: "engineering",
    stack: ["kotlin", "java", "kafka"],
    culture: "scaleup",
    teamSize: 80,
    onCall: true,
    fourDayWeek: false,
    summary: "Konto und Ledger, Kafka, Bereitschaft alle sechs Wochen.",
  },
  {
    id: "tr-fe",
    company: "Trade Republic",
    role: "Senior Frontend Engineer",
    city: "Berlin",
    workMode: "hybrid",
    salaryMin: 90,
    salaryMax: 120,
    seniority: "senior",
    fn: "engineering",
    stack: ["react", "typescript", "react-native"],
    culture: "scaleup",
    teamSize: 35,
    onCall: false,
    fourDayWeek: false,
    summary: "Trading-UI in React Native, hohe Geschwindigkeit, Berlin.",
  },
  {
    id: "celonis-data",
    company: "Celonis",
    role: "Data Scientist",
    city: "München",
    workMode: "hybrid",
    salaryMin: 85,
    salaryMax: 110,
    seniority: "senior",
    fn: "data",
    stack: ["python", "sql", "spark"],
    culture: "scaleup",
    teamSize: 50,
    onCall: false,
    fourDayWeek: false,
    summary: "Process Mining, Spark, Enterprise, München oder Remote-DE.",
  },
  {
    id: "gyg-pm",
    company: "GetYourGuide",
    role: "Senior Product Manager",
    city: "Berlin",
    workMode: "hybrid",
    salaryMin: 90,
    salaryMax: 115,
    seniority: "senior",
    fn: "product",
    stack: ["analytics", "sql", "figma"],
    culture: "scaleup",
    teamSize: 22,
    onCall: false,
    fourDayWeek: false,
    summary: "Marktplatz für Tours, PM mit SQL und Discovery in Berlin.",
  },
  {
    id: "contentful-pm",
    company: "Contentful",
    role: "Product Manager",
    city: "Berlin",
    workMode: "remote",
    salaryMin: 80,
    salaryMax: 100,
    seniority: "mid",
    fn: "product",
    stack: ["b2b", "api", "analytics"],
    culture: "scaleup",
    teamSize: 16,
    onCall: false,
    fourDayWeek: false,
    summary: "Headless CMS, API-First, Remote in Deutschland.",
  },
  {
    id: "adjust-mkt",
    company: "Adjust",
    role: "Product Marketing Manager",
    city: "Berlin",
    workMode: "hybrid",
    salaryMin: 70,
    salaryMax: 90,
    seniority: "mid",
    fn: "marketing",
    stack: ["b2b", "positioning", "sales"],
    culture: "scaleup",
    teamSize: 12,
    onCall: false,
    fourDayWeek: false,
    summary: "Mobile Attribution, Launches, Messaging für Sales.",
  },
  {
    id: "zalando-ae",
    company: "Zalando",
    role: "Account Executive",
    city: "Berlin",
    workMode: "onsite",
    salaryMin: 65,
    salaryMax: 90,
    seniority: "mid",
    fn: "sales",
    stack: ["saas", "outbound"],
    culture: "corporate",
    teamSize: 120,
    onCall: false,
    fourDayWeek: false,
    summary: "Partner-SaaS, Quota, vor Ort am Campus.",
  },
  {
    id: "sap-se",
    company: "SAP",
    role: "Senior Software Engineer",
    city: "München",
    workMode: "hybrid",
    salaryMin: 85,
    salaryMax: 105,
    seniority: "senior",
    fn: "engineering",
    stack: ["java", "cloud", "abap"],
    culture: "corporate",
    teamSize: 200,
    onCall: true,
    fourDayWeek: false,
    summary: "Cloud und Java, Kernzeit, On-Call in manchen Teams.",
  },
  {
    id: "siemens-de",
    company: "Siemens",
    role: "Data Engineer",
    city: "München",
    workMode: "hybrid",
    salaryMin: 78,
    salaryMax: 98,
    seniority: "mid",
    fn: "data",
    stack: ["python", "spark", "azure"],
    culture: "corporate",
    teamSize: 90,
    onCall: false,
    fourDayWeek: false,
    summary: "Industrie-Daten in Azure, Shopfloor bis Cloud.",
  },
  {
    id: "delivery-fe",
    company: "Delivery Hero",
    role: "Frontend Engineer",
    city: "Berlin",
    workMode: "hybrid",
    salaryMin: 72,
    salaryMax: 92,
    seniority: "mid",
    fn: "engineering",
    stack: ["react", "typescript"],
    culture: "scaleup",
    teamSize: 45,
    onCall: true,
    fourDayWeek: false,
    summary: "Storefront für viele Märkte, React, On-Call im Platform-Team.",
  },
  {
    id: "hellofresh-ds",
    company: "HelloFresh",
    role: "Senior Data Analyst",
    city: "Berlin",
    workMode: "hybrid",
    salaryMin: 75,
    salaryMax: 95,
    seniority: "senior",
    fn: "data",
    stack: ["sql", "dbt", "looker"],
    culture: "scaleup",
    teamSize: 30,
    onCall: false,
    fourDayWeek: false,
    summary: "Supply Chain und Growth, dbt und Looker, drei Tage Office.",
  },
  {
    id: "coba-pm",
    company: "Commerzbank",
    role: "IT Project Manager",
    city: "Frankfurt",
    workMode: "onsite",
    salaryMin: 80,
    salaryMax: 100,
    seniority: "senior",
    fn: "product",
    stack: ["waterfall", "banking"],
    culture: "corporate",
    teamSize: 150,
    onCall: false,
    fourDayWeek: false,
    summary: "Banking-Vorhaben, Waterfall, Präsenz in Frankfurt.",
  },
  {
    id: "sumup-ios",
    company: "SumUp",
    role: "iOS Engineer",
    city: "Berlin",
    workMode: "hybrid",
    salaryMin: 80,
    salaryMax: 105,
    seniority: "senior",
    fn: "engineering",
    stack: ["swift", "ios"],
    culture: "scaleup",
    teamSize: 20,
    onCall: false,
    fourDayWeek: false,
    summary: "Händler-App in Swift, Terminal-Nähe, Hybrid.",
  },
  {
    id: "typeform-growth",
    company: "Typeform",
    role: "Growth Lead",
    city: "Remote",
    workMode: "remote",
    salaryMin: 85,
    salaryMax: 110,
    seniority: "lead",
    fn: "marketing",
    stack: ["growth", "analytics", "seo"],
    culture: "startup",
    teamSize: 9,
    onCall: false,
    fourDayWeek: true,
    summary: "Acquisition und Activation, SEO, vier Tage, Remote EU.",
  },
  {
    id: "figma-pd",
    company: "Figma",
    role: "Product Designer",
    city: "Berlin",
    workMode: "hybrid",
    salaryMin: 105,
    salaryMax: 145,
    seniority: "senior",
    fn: "design",
    stack: ["figma", "systems", "research"],
    culture: "scaleup",
    teamSize: 15,
    onCall: false,
    fourDayWeek: false,
    summary: "Du designst das Tool, in dem andere designen. Berlin Hub.",
  },
  {
    id: "vercel-dx",
    company: "Vercel",
    role: "Developer Experience Engineer",
    city: "Remote",
    workMode: "remote",
    salaryMin: 100,
    salaryMax: 140,
    seniority: "senior",
    fn: "engineering",
    stack: ["nextjs", "typescript", "react"],
    culture: "startup",
    teamSize: 11,
    onCall: false,
    fourDayWeek: false,
    summary: "Next.js und CLI, weltweites Remote, kein Konzern.",
  },
  {
    id: "ottonova-be",
    company: "Ottonova",
    role: "Go Engineer",
    city: "München",
    workMode: "remote",
    salaryMin: 80,
    salaryMax: 100,
    seniority: "senior",
    fn: "engineering",
    stack: ["go", "grpc", "postgres"],
    culture: "startup",
    teamSize: 10,
    onCall: false,
    fourDayWeek: false,
    summary: "Krankenversicherung, Go und gRPC, Remote in DACH.",
  },
  {
    id: "staffbase-sales",
    company: "Staffbase",
    role: "Account Executive DACH",
    city: "Chemnitz",
    workMode: "hybrid",
    salaryMin: 70,
    salaryMax: 95,
    seniority: "mid",
    fn: "sales",
    stack: ["b2b", "enterprise"],
    culture: "scaleup",
    teamSize: 28,
    onCall: false,
    fourDayWeek: false,
    summary: "Enterprise-Comms, lange Cycles, Hybrid aus Chemnitz.",
  },
  {
    id: "linear-pe",
    company: "Linear",
    role: "Product Engineer",
    city: "Berlin",
    workMode: "hybrid",
    salaryMin: 95,
    salaryMax: 130,
    seniority: "senior",
    fn: "engineering",
    stack: ["typescript", "react", "postgres"],
    culture: "startup",
    teamSize: 10,
    onCall: false,
    fourDayWeek: true,
    summary: "Du baust das, was Designer zeichnen. TypeScript, vier Tage möglich.",
  },
  {
    id: "langfuse-pd",
    company: "Langfuse",
    role: "Founding Product Designer",
    city: "Berlin",
    workMode: "hybrid",
    salaryMin: 75,
    salaryMax: 100,
    seniority: "senior",
    fn: "design",
    stack: ["figma", "research", "product"],
    culture: "startup",
    teamSize: 3,
    onCall: false,
    fourDayWeek: false,
    summary: "Erster Designer, LLM-Tooling, du setzt die Sprache.",
  },
  {
    id: "figma-de",
    company: "Figma",
    role: "Design Engineer",
    city: "Berlin",
    workMode: "hybrid",
    salaryMin: 110,
    salaryMax: 150,
    seniority: "senior",
    fn: "engineering",
    stack: ["typescript", "react", "figma"],
    culture: "scaleup",
    teamSize: 9,
    onCall: false,
    fourDayWeek: false,
    summary: "Zwischen Editor und Code, Multiplayer, Pixel und Performance.",
  },
  {
    id: "raycast-macos",
    company: "Raycast",
    role: "macOS Engineer",
    city: "Remote",
    workMode: "remote",
    salaryMin: 105,
    salaryMax: 140,
    seniority: "senior",
    fn: "engineering",
    stack: ["swift", "macos", "typescript"],
    culture: "startup",
    teamSize: 7,
    onCall: false,
    fourDayWeek: true,
    summary: "Swift, AppKit, Extensions. Remote, vier Tage.",
  },
  {
    id: "polar-pd",
    company: "Polar",
    role: "Product Designer",
    city: "Remote",
    workMode: "remote",
    salaryMin: 82,
    salaryMax: 108,
    seniority: "senior",
    fn: "design",
    stack: ["figma", "systems"],
    culture: "startup",
    teamSize: 5,
    onCall: false,
    fourDayWeek: true,
    summary: "Payments für Open Source, du designst Billing ohne Konzern-Look.",
  },
  {
    id: "n26-spd",
    company: "N26",
    role: "Staff Product Designer",
    city: "Berlin",
    workMode: "hybrid",
    salaryMin: 110,
    salaryMax: 140,
    seniority: "staff",
    fn: "design",
    stack: ["figma", "systems", "research"],
    culture: "scaleup",
    teamSize: 22,
    onCall: false,
    fourDayWeek: false,
    summary: "Staff-IC, Konto und Card, Systems über mehrere Squads.",
  },
  {
    id: "vercel-pd",
    company: "Vercel",
    role: "Product Designer",
    city: "Remote",
    workMode: "remote",
    salaryMin: 100,
    salaryMax: 135,
    seniority: "senior",
    fn: "design",
    stack: ["figma", "systems", "product"],
    culture: "startup",
    teamSize: 8,
    onCall: false,
    fourDayWeek: false,
    summary: "Dashboard, Deployments, DX. Remote, hohes Niveau.",
  },
  {
    id: "celonis-pd",
    company: "Celonis",
    role: "Senior Product Designer",
    city: "München",
    workMode: "hybrid",
    salaryMin: 88,
    salaryMax: 115,
    seniority: "senior",
    fn: "design",
    stack: ["figma", "research", "b2b"],
    culture: "scaleup",
    teamSize: 18,
    onCall: false,
    fourDayWeek: false,
    summary: "Process Mining sichtbar machen, Enterprise-UX, München.",
  },
];

export function jobById(id: string) {
  return JOBS.find((job) => job.id === id) ?? null;
}

export const JOBS: Job[] = RAW_JOBS.map((job) => {
  const details = JOB_DETAILS[job.id];
  if (!details) {
    throw new Error(`Missing job details for ${job.id}`);
  }
  return {
    ...job,
    description: details.description,
    responsibilities: details.responsibilities,
    requirements: details.requirements,
  };
});
